#!/bin/sh
NAME=ciop-sandbox
OS=RedHat
IMAGE=/tmp/${NAME}.vmdk
SZMB=512
INSTDIR=/tmp/boxes/
BUILDDIR=/tmp/builds/
CURDIR=`dirname $0`

mkdir -p ${BUILDDIR} ${INSTDIR}
cat > ${BUILDDIR}/${NAME}.appl << EOF
name: ${NAME}
summary: CIOP Sandbox (Scientific Linux)
os:
  name: sl
  version: 6
hardware:
  partitions:
    "/":
      size: 5
packages:
  - "acl"
  - "aic94xx-firmware"
  - "atmel-firmware"
  - "attr"
  - "audit"
  - "audit-libs"
  - "authconfig"
  - "b43-openfwwf"
  - "basesystem"
  - "bash"
  - "bfa-firmware"
  - "binutils"
  - "bzip2"
  - "bzip2-libs"
  - "ca-certificates"
  - "checkpolicy"
  - "chkconfig"
  - "coreutils"
  - "coreutils-libs"
  - "cpio"
  - "cracklib-dicts"
  - "cracklib"
  - "cronie-anacron"
  - "cronie"
  - "crontabs"
  - "curl"
  - "cyrus-sasl"
  - "cyrus-sasl-lib"
  - "dash"
  - "db4"
  - "db4-utils"
  - "dbus-glib"
  - "dbus-libs"
  - "device-mapper-event-libs"
  - "device-mapper-event"
  - "device-mapper"
  - "device-mapper-libs"
  - "dhclient"
  - "diffutils"
  - "dracut-kernel"
  - "dracut"
  - "e2fsprogs"
  - "e2fsprogs-libs"
  - "efibootmgr"
  - "elfutils-libelf"
  - "ethtool"
  - "expat"
  - "file-libs"
  - "filesystem"
  - "findutils"
  - "fipscheck"
  - "fipscheck-lib"
  - "gamin"
  - "gawk"
  - "gdbm"
  - "glib2"
  - "gmp"
  - "gnupg2"
  - "gpgme"
  - "grep"
  - "grubby"
  - "grub"
  - "gzip"
  - "hwdata"
  - "info"
  - "initscripts"
  - "iproute"
  - "iptables"
  - "iptables-ipv6"
  - "iputils"
  - "ipw2100-firmware"
  - "ipw2200-firmware"
  - "ivtv-firmware"
  - "iwl1000-firmware"
  - "iwl100-firmware"
  - "iwl3945-firmware"
  - "iwl4965-firmware"
  - "iwl5000-firmware"
  - "iwl5150-firmware"
  - "iwl6000-firmware"
  - "iwl6000g2a-firmware"
  - "iwl6000g2b-firmware"
  - "iwl6050-firmware"
  - "kbd"
  - "kbd-misc"
  - "kernel-firmware"
  - "kernel"
  - "keyutils-libs"
  - "krb5-libs"
  - "less"
  - "libacl"
  - "libattr"
  - "libblkid"
  - "libcap"
  - "libcap-ng"
  - "libcom_err"
  - "libcurl"
  - "libdrm"
  - "libertas-usb8388-firmware"
  - "libffi"
  - "libgcc"
  - "libgcrypt"
  - "libgpg-error"
  - "libidn"
  - "libnih"
  - "libselinux"
  - "libselinux-utils"
  - "libsemanage"
  - "libsepol"
  - "libssh2"
  - "libss"
  - "libstdc++"
  - "libudev"
  - "libusb"
  - "libuser"
  - "libutempter"
  - "libuuid"
  - "libxml2"
  - "logrotate"
  - "lua"
  - "lvm2"
  - "lvm2-libs"
  - "m4"
  - "MAKEDEV"
  - "mingetty"
  - "module-init-tools"
  - "mysql-libs"
  - "ncurses-base"
  - "ncurses"
  - "ncurses-libs"
  - "net-tools"
  - "netxen-firmware"
  - "newt"
  - "newt-python"
  - "nspr"
  - "nss"
  - "nss-softokn-freebl"
  - "nss-softokn"
  - "nss-sysinit"
  - "nss-util"
  - "openldap"
  - "openssh"
  - "openssh-server"
  - "openssl"
  - "pam"
  - "passwd"
  - "pciutils-libs"
  - "pcre"
  - "pinentry"
  - "plymouth-core-libs"
  - "plymouth"
  - "plymouth-scripts"
  - "policycoreutils"
  - "popt"
  - "postfix"
  - "procps"
  - "psmisc"
  - "pth"
  - "pygpgme"
  - "python"
  - "python-iniparse"
  - "python-libs"
  - "python-pycurl"
  - "python-urlgrabber"
  - "ql2100-firmware"
  - "ql2200-firmware"
  - "ql23xx-firmware"
  - "ql2400-firmware"
  - "ql2500-firmware"
  - "readline"
  - "redhat-logos"
  - "rootfiles"
  - "rpm"
  - "rpm-libs"
  - "rpm-python"
  - "rt61pci-firmware"
  - "rt73usb-firmware"
  - "sed"
  - "selinux-policy"
  - "selinux-policy-targeted"
  - "setup"
  - "shadow-utils"
  - "slang"
  - "sl-release"
  - "sqlite"
  - "sudo"
  - "system-config-firewall-base"
  - "sysvinit-tools"
  - "tar"
  - "tcp_wrappers-libs"
  - "tzdata"
  - "udev"
  - "upstart"
  - "ustr"
  - "util-linux-ng"
  - "vim-minimal"
  - "which"
  - "xorg-x11-drv-ati-firmware"
  - "xz-libs"
  - "yum-autoupdate"
  - "yum-conf-sl-other"
  - "yum-metadata-parser"
  - "yum"
  - "zd1211-firmware"
  - "zlib"
files:
  "/tmp":
    - "custom-${NAME}.sh"
    - "eosec-unix-info_v200.sh"
post:
  base:
   - "echo secret | passwd root --stdin"
EOF

#   - "/bin/sh -x /tmp/custom-${NAME}.sh > /tmp/custom-${NAME}.log"

cp ${CURDIR}/custom-${NAME}.sh       ${BUILDDIR}
cp ${CURDIR}/eosec-unix-info_v200.sh ${BUILDDIR}

cd ${BUILDDIR}

sudo -E setarch i386 boxgrinder-build --trace -p virtualbox ${NAME}.appl && \
cp ${BUILDDIR}/build/appliances/i686/sl/6/${NAME}/1.0/virtualbox-plugin/${NAME}.vmdk ${IMAGE} && \
VBoxManage createvm --name ${NAME} --ostype ${OS} --register --basefolder ${INSTDIR} && \
VBoxManage modifyvm ${NAME} --memory ${SZMB} --vram 12 --rtcuseutc on --largepages on && \
VBoxManage modifyvm ${NAME} --boot1 dvd --boot2 disk --boot3 none --boot4 none && \
VBoxManage modifyvm ${NAME} --hwvirtexexcl off && \
VBoxManage modifyvm ${NAME} --nictype1 82540EM --macaddress1 0800273C6A56 && \
VBoxManage modifyvm ${NAME} --natpf1 "Rule 1,tcp,,3333,,22" && \
VBoxManage modifyvm ${NAME} --nictype2 82540EM --macaddress2 0800274C41E7 && \
VBoxManage modifyvm ${NAME} --nic2 intnet && \
VBoxManage modifyvm ${NAME} --intnet2 g-pod && \
VBoxManage storagectl ${NAME} --name "IDE-Controller" --add ide && \
VBoxManage storageattach ${NAME} --storagectl "IDE-Controller" --type dvddrive --port 1 --device 0 --medium emptydrive && \
VBoxManage storagectl ${NAME} --name "SATA-Controller" --add sata --sataportcount 1 && \
VBoxManage storageattach ${NAME} --storagectl "SATA-Controller" --type hdd --port 1 --device 0 --medium ${IMAGE}
# VBoxManage export ${NAME} --manifest -o ${BUILDDIR}/${NAME}.ova
# VirtualBox --startvm ${NAME}
